### ISSUE TITLE
Create `private` repo to house private tasks (issues)

### ISSUE THREAD

**Issue by jonmatthis** [jpforpalestine/jpforpalestine#11]
(I believe) the visibility of a Task (Issue) is determined by the visiblity of its housing repository. 

Right now, all the Issues on this project board are owned by the default jp4p repo (which is public), so I will make an additional `jpforpalestine/_private` repo to house info and issues that we don't want to be public

> Note - a leading underscore is often used in code to denote a 'private' variable, i.e. one that should not be accessed from the outside

## Sub-tasks

- [ ] Make the repo at: https://github.com/jpforpalestine/_private
- [ ] Create dummy issues: https://github.com/jpforpalestine/_private/issues/1
- test visibility  by members/non-members ( @lishtran - Can you see the issue linked above?) 
- [ ] Research:  how private/secure is a 'private' GH repo? Best practices?
